#!/usr/bin/env python3
"""credits.py - CREDITS.md that writes itself ("fmt credits"), format v0.1.
Usage: python3 tools/credits.py <game-dir>

Merges three sources of contribution, because communities are bigger than
committers:
  1. community.yaml contributors (declared roles)
  2. git authors on this game's files (commit counts)
  3. playtest session players (sessions attended — testers never touch git,
     they get credited anyway)
Writes <game-dir>/CREDITS.md. On the platform this renders as the credit roll.
"""
import json, subprocess, sys
from collections import defaultdict
from pathlib import Path
import yaml

game_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else None
if not game_dir: sys.exit("Usage: python3 tools/credits.py <game-dir>")

people = defaultdict(lambda: {"roles": set(), "commits": 0, "sessions": 0, "since": None, "url": None})

# 1. declared contributors
cy = game_dir / "community.yaml"
if cy.exists():
    for c in (yaml.safe_load(cy.read_text()) or {}).get("contributors") or []:
        p = people[c["name"]]
        p["roles"] |= set(c.get("roles") or [])
        p["since"] = p["since"] or c.get("since")
        p["url"] = p["url"] or c.get("url")

# 2. git authors on this game's path
try:
    log = subprocess.run(
        ["git", "log", "--format=%an", "--", "."],
        capture_output=True, text=True, cwd=game_dir, check=True).stdout.splitlines()
    for a in log:
        if a.strip():
            people[a.strip()]["commits"] += 1
            people[a.strip()]["roles"].add("developer")
except Exception:
    pass  # not a git repo — declared + playtesters still work

# 3. playtesters
pt = game_dir / "playtests"
if pt.is_dir():
    for f in sorted(pt.glob("*.json")):
        for pl in json.loads(f.read_text()).get("players") or []:
            people[pl["name"]]["sessions"] += 1
            people[pl["name"]]["roles"].add("playtester")

ROLE_ORDER = ["lead designer", "developer", "artist", "editor", "rules editor", "translator", "playtester", "community"]
def role_key(roles):
    for i, r in enumerate(ROLE_ORDER):
        if r in roles: return i
    return len(ROLE_ORDER)

game = yaml.safe_load((game_dir / "game.yaml").read_text())
lines = [f"# Credits — {game.get('title', '?')}", "",
         "*Generated by `fmt credits` from community.yaml, git history, and playtest logs.*", ""]
for name, p in sorted(people.items(), key=lambda kv: (role_key(kv[1]["roles"]), kv[0].lower())):
    roles = ", ".join(sorted(p["roles"], key=lambda r: ROLE_ORDER.index(r) if r in ROLE_ORDER else 99))
    extras = []
    if p["commits"]: extras.append(f"{p['commits']} commit{'s' if p['commits'] != 1 else ''}")
    if p["sessions"]: extras.append(f"{p['sessions']} playtest session{'s' if p['sessions'] != 1 else ''}")
    if p["since"]: extras.append(f"since {p['since']}")
    lines.append(f"- **{name}** — {roles}" + (f" *({', '.join(extras)})*" if extras else ""))
lines += ["", "Playtesters are credited automatically from `playtests/*.json` — showing up to break the game is a contribution."]

out = game_dir / "CREDITS.md"
out.write_text("\n".join(lines) + "\n")
print(f"Credits → {out}  ({len(people)} people)")
for l in lines[4:4 + len(people)]: print("  " + l)
