#!/usr/bin/env python3
"""export_nandeck.py - nanDECK project exporter (interop bridge), format v0.1.

Usage: python3 tools/export_nandeck.py <game-dir>
Output: exports/nandeck/<slug>.csv   one row per physical card (quantities pre-expanded)
        exports/nandeck/<slug>.txt   a nanDECK script that binds to the CSV columns

INTEROP BRIDGE - nanDECK (https://nandeck.com) is a free, powerful card-layout
tool. This does NOT run nanDECK and adds NO runtime dependency; it emits a
nanDECK PROJECT (a .txt script + a .csv) that a designer opens in their own copy
to get professional layout, a print-ready PDF, or a direct Tabletop Simulator
export. Your platform data stays canonical - this is a one-way data->text bridge.

Mapping: your data/layout split IS nanDECK's split. cards.json + printings.json
-> LINK=<slug>.csv (one row per card); templates -> the script's directives.
Rules-text symbol tokens like [spark] are rewritten to (spark) so they don't
collide with nanDECK's own [column] syntax; wire ICON= directives for real art.
The CSV is exact; the script is a sensible starting layout - tweak it in nanDECK.
"""
import csv, json, re, sys
from pathlib import Path
import yaml

CARD_W_MM, CARD_H_MM = 63, 88  # standard poker card, millimetres (matches CARDSIZE)


def slugify(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-") or "game"


def safe_text(s):
    # nanDECK reads [col] as a column reference; keep card symbol tokens from colliding
    return (s or "").replace("[", "(").replace("]", ")")


def main():
    game_dir = Path(sys.argv[1])
    game = yaml.safe_load((game_dir / "game.yaml").read_text())
    cards = {c["id"]: c for c in json.loads((game_dir / "components/cards.json").read_text())}
    printings = json.loads((game_dir / "components/printings.json").read_text())

    title = game.get("title", game_dir.name)
    slug = slugify(title)
    out_dir = game_dir / "exports" / "nandeck"
    out_dir.mkdir(parents=True, exist_ok=True)

    attr_keys = sorted({k for c in cards.values() for k in (c.get("attributes") or {}).keys()})
    header = (["id", "name", "type", "subtypes", "keywords", "text"] + attr_keys +
              ["set", "collector_number", "variant", "artist", "art", "qty"])

    rows = []
    for p in printings:
        c = cards.get(p["card_id"], {})
        prov = p.get("provenance") or {}
        row = {
            "id": c.get("id", p["card_id"]),
            "name": c.get("name", p["card_id"]),
            "type": c.get("type", ""),
            "subtypes": ";".join(c.get("subtypes") or []),
            "keywords": ";".join(c.get("keywords") or []),
            "text": safe_text(c.get("text", "")),
            "set": p.get("set_id", ""),
            "collector_number": p.get("collector_number", ""),
            "variant": p.get("variant") or "",
            "artist": p.get("artist") or prov.get("creator") or "",
            "art": p.get("art") or "",
            "qty": p.get("quantity", 1),
        }
        for k in attr_keys:
            row[k] = (c.get("attributes") or {}).get(k, "")
        # one row per physical card -> the deck renders correctly with no quantity directive
        for _ in range(int(p.get("quantity", 1) or 1)):
            rows.append(row)

    csv_path = out_dir / f"{slug}.csv"
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=header)
        w.writeheader()
        w.writerows(rows)

    # Compatibility exporter. The plugin registry now dispatches to the
    # family-aware Node bridge; keep direct legacy invocations dimensionally
    # correct because nanDECK otherwise defaults to centimetres.
    L = [
        "; Legacy nanDECK script generated by tabletop-format. Prefer: fmt export nandeck <game-dir>",
        f"; Deck: {title}.  Data: {slug}.csv (one row per physical card; quantities pre-expanded).",
        "; Coordinates are in millimetres. Text-only layout by default;",
        "; add IMAGE=/ICON= directives for card art and rules symbols.",
        "",
        "UNIT=MM",
        f"LINK={slug}.csv",
        f"CARDSIZE={CARD_W_MM},{CARD_H_MM}",
        "BORDER=RECTANGLE,1,000000",
        "",
        "FONT=Arial,9,B,000000",
        'TEXT=,"[name]",3,3,45,8,left',
    ]
    if "cost" in attr_keys:
        L += ["FONT=Arial,9,B,B00000", 'TEXT=,"[cost]",48,3,12,8,right']
    L += [
        "FONT=Arial,7,I,606060",
        'TEXT=,"[type]",3,12,57,6,left',
        "FONT=Arial,8,,000000",
        'TEXT=,"[text]",4,22,55,52,left,wordwrap',
        "FONT=Arial,6,,909090",
        'TEXT=,"[set] [collector_number]",3,80,57,5,right',
        "",
        "; --- optional art: uncomment and make sure [art] paths resolve from this folder ---",
        '; IMAGE=,"[art]",0,0,63,88,0,MF',
    ]
    (out_dir / f"{slug}.txt").write_text("\n".join(L) + "\n")

    print(f"nanDECK project: exports/nandeck/{slug}.txt + {slug}.csv  "
          f"({len(rows)} cards from {len(printings)} printings, {len(attr_keys)} attribute column(s))")
    print(f"  open {slug}.txt in nanDECK -> layout / print-ready PDF / direct TTS export")


if __name__ == "__main__":
    main()
