#!/usr/bin/env python3
"""export_ttc.py — Tabletop Club asset-pack exporter, format v0.1.

Usage: python3 tools/export_ttc.py <game-dir>
Output: exports/ttc/<PackName>/   (the asset pack, drop into TabletopClub/assets/)
        exports/ttc/<slug>-ttc.zip (distributable — unzip into assets/)

Tabletop Club (https://tabletopclub.net) is the free, open-source, MIT-licensed
3D tabletop playspace. Unlike TTS, an asset pack is a FOLDER of individual card
images plus plain-text .cfg config — no sprite sheet, no hosted URLs, no
proprietary tool anywhere in the chain. Because TTC has per-asset `license`,
`author`, and `url` fields, this exporter carries our provenance model straight
into the play environment: credit follows the work onto the 3D table.

Spec: https://docs.tabletopclub.net/en/stable/custom_assets/asset_packs/
  cards/            one image per card face + a shared _back.png
  cards/config.cfg  [*] back_face/scale/license/author; [<file>] desc + per-card author
  cards/stacks.cfg  [<Deck>] items = [...] — the pre-filled deck, honoring quantities
"""
import json, re, sys, shutil
from pathlib import Path

import yaml

# standard poker card, centimetres (TTC scale is physical size)
CARD_W_CM, CARD_H_CM = 6.35, 8.89


def sanitize(name):
    """Filesystem- and cfg-safe asset name. TTC's in-game name defaults to the
    file name without extension, so keep it human-readable (spaces are fine)."""
    return re.sub(r'[\\/:*?"<>|]+', "-", name).strip() or "card"


def cfg_str(s):
    """Quote a value for a Godot .cfg file (escape quotes + newlines kept literal)."""
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    game_dir = Path(sys.argv[1])
    game = yaml.safe_load((game_dir / "game.yaml").read_text())
    cards = {c["id"]: c for c in json.loads((game_dir / "components/cards.json").read_text())}
    printings = json.loads((game_dir / "components/printings.json").read_text())
    faces_dir = game_dir / "exports" / "faces"
    if not faces_dir.is_dir():
        raise SystemExit("No rendered faces — run: python3 tools/render_cards.py <game-dir>")

    title = game.get("title", game_dir.name)
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-") or game_dir.name
    game_license = game.get("license", "")
    game_authors = ", ".join(a.get("name", "") for a in (game.get("authors") or [])) or ""
    default_creator = (game.get("default_provenance") or {}).get("creator", "")

    out_root = game_dir / "exports" / "ttc"
    if out_root.exists():
        shutil.rmtree(out_root)
    pack = out_root / sanitize(title)          # folder name = pack name (what TTC scans)
    cards_dir = pack / "cards"
    cards_dir.mkdir(parents=True)

    # a card name may appear across several printings (reprints, alt-arts):
    # in-game names must be UNIQUE per type, so disambiguate collisions.
    name_counts = {}
    for p in printings:
        nm = cards.get(p["card_id"], {}).get("name", p["card_id"])
        name_counts[nm] = name_counts.get(nm, 0) + 1

    per_card_cfg = []   # (filename, desc, author-or-None)
    stack_items = []    # in-game names, repeated by quantity
    used = set()

    # shared back face
    back_src = faces_dir / "_back.png"
    if back_src.exists():
        shutil.copy(back_src, cards_dir / "_back.png")

    for p in printings:
        face = faces_dir / f"{p['id']}.png"
        if not face.exists():
            continue
        card = cards.get(p["card_id"], {})
        base = card.get("name", p["card_id"])
        # disambiguate reprints with the variant or collector number
        name = base
        if name_counts.get(base, 0) > 1:
            tag = p.get("variant") or p.get("collector_number") or p["id"]
            name = f"{base} ({tag})"
        name = sanitize(name)
        while name in used:                    # last-resort uniqueness
            name = f"{name}-{p['id'][-4:]}"
        used.add(name)

        shutil.copy(face, cards_dir / f"{name}.png")

        # per-card description = the rules text; author = the credit that made THIS printing
        prov = p.get("provenance") or {}
        creator = p.get("artist") or prov.get("creator") or ""
        author = creator if creator and creator != default_creator else None
        per_card_cfg.append((f"{name}.png", card.get("text", ""), author))

        stack_items.extend([name] * int(p.get("quantity", 1)))

    # ---- cards/config.cfg ----
    lines = ["; Generated by tabletop-format — Tabletop Club asset pack.",
             "; One image per card face; the deck is defined in stacks.cfg.",
             "", "[*]", 'back_face = "_back.png"',
             f"scale = Vector2({CARD_W_CM}, {CARD_H_CM})"]
    if game_license: lines.append(f"license = {cfg_str(game_license)}")
    if game_authors: lines.append(f"author = {cfg_str(game_authors)}")
    lines.append("")
    for fname, desc, author in per_card_cfg:
        if not desc and not author:
            continue
        lines.append(f"[{fname}]")
        if desc:   lines.append(f"desc = {cfg_str(desc)}")
        if author: lines.append(f"author = {cfg_str(author)}   ; provenance: credit follows the work")
        lines.append("")
    (cards_dir / "config.cfg").write_text("\n".join(lines) + "\n")

    # ---- cards/stacks.cfg (the playable deck) ----
    desc = (game.get("description", "") or "").strip().replace("\n", " ")
    items = ",\n    ".join(cfg_str(n) for n in stack_items)
    (cards_dir / "stacks.cfg").write_text(
        f"; The ready-to-play deck, honoring per-card quantities.\n"
        f"[{sanitize(title)} Deck]\n"
        + (f"desc = {cfg_str(desc)}\n" if desc else "")
        + f"items = [\n    {items}\n]\n")

    # ---- distributable zip (unzip into TabletopClub/assets/) ----
    zip_base = out_root / f"{slug}-ttc"
    shutil.make_archive(str(zip_base), "zip", root_dir=out_root, base_dir=sanitize(title))

    n_faces = len(stack_items)
    n_unique = len(used)
    print(f"Tabletop Club pack: {pack.relative_to(game_dir)}  "
          f"({n_unique} unique cards, {n_faces}-card deck)")
    print(f"  distributable:     exports/ttc/{slug}-ttc.zip")
    print(f"  install: unzip into <Documents>/TabletopClub/assets/  →  play as '{title}'")


if __name__ == "__main__":
    main()
