#!/usr/bin/env node
/**
 * fmt-git.mjs — git porcelain for game designers. ZERO dependencies (shells to git).
 * This is "git for board games" as product verbs:
 *
 *   save <game-dir> [-m msg]     commit everything; if cards changed, the
 *                                COMMIT MESSAGE WRITES ITSELF from the semantic diff
 *   history <game-dir> [-n N]    git log rendered as card changes, not hashes
 *   changelog <game-dir>         write CHANGELOG.md from the full card history
 *   fork <src.git> <dst.git>     server-side fork (bare clone) — the Remix primitive
 *   release <game-dir> <x.y.z>   annotated tag with the changelog since last release
 *   setup <game-dir>             enable the semantic `git diff` driver in this clone
 *
 * The game dir must live inside a git repo (any level). Everything here is a
 * thin veneer over plain git — which is the point: your game IS a repo.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { diffCards, summarize, formatChanges } from "./lib/carddiff.mjs";

const TOOLS = dirname(fileURLToPath(import.meta.url));
const [cmd, ...rest] = process.argv.slice(2);

function git(repoDir, args, opts = {}) {
  return execFileSync("git", ["-C", repoDir, ...args], { encoding: "utf8", ...opts }).trimEnd();
}
function repoOf(gameDir) { return git(gameDir, ["rev-parse", "--show-toplevel"]); }
function cardsRel(gameDir, repo) { return relative(repo, resolve(gameDir, "components/cards.json")); }
function cardsAt(repo, ref, rel) {
  try { return JSON.parse(git(repo, ["show", `${ref}:${rel}`])); } catch { return null; }
}

if (cmd === "save") {
  const gameDir = resolve(rest[0]);
  const mIdx = rest.indexOf("-m");
  const userMsg = mIdx > -1 ? rest[mIdx + 1] : null;
  const repo = repoOf(gameDir);
  const rel = cardsRel(gameDir, repo);
  const before = cardsAt(repo, "HEAD", rel) ?? [];
  const after = existsSync(join(gameDir, "components/cards.json"))
    ? JSON.parse(readFileSync(join(gameDir, "components/cards.json"), "utf8")) : [];
  const changes = diffCards(before, after);
  const auto = summarize(changes);
  const otherChanges = git(repo, ["status", "--porcelain", "--", relative(repo, gameDir)]);
  if (!otherChanges) { console.log("Nothing to save."); process.exit(0); }
  const title = userMsg ?? auto?.title ?? "update game files";
  const msg = auto ? `${title}\n\n${auto.body}` : title;
  git(repo, ["add", "--", relative(repo, gameDir)]);
  git(repo, ["commit", "-m", msg]);
  console.log(`Saved: ${title}`);
  if (auto) console.log(auto.body.split("\n").map(l => "  " + l).join("\n"));
}

else if (cmd === "history") {
  const gameDir = resolve(rest[0]);
  const nIdx = rest.indexOf("-n");
  const limit = nIdx > -1 ? parseInt(rest[nIdx + 1], 10) : 20;
  const repo = repoOf(gameDir);
  const rel = cardsRel(gameDir, repo);
  const log = git(repo, ["log", `-${limit}`, "--format=%H|%h|%an|%as|%s", "--", rel]);
  if (!log) { console.log("No card history yet."); process.exit(0); }
  for (const line of log.split("\n")) {
    const [full, short, author, date, subject] = line.split("|");
    const now = cardsAt(repo, full, rel) ?? [];
    const prev = cardsAt(repo, `${full}^`, rel) ?? [];
    const changes = diffCards(prev, now);
    console.log(`\n● ${short}  ${date}  ${author} — ${subject}`);
    if (!prev.length && now.length) console.log(`  + ${now.length} cards introduced`);
    else console.log(formatChanges(changes).split("\n").map(l => "  " + l).join("\n"));
  }
}

else if (cmd === "changelog") {
  const gameDir = resolve(rest[0]);
  const repo = repoOf(gameDir);
  const rel = cardsRel(gameDir, repo);
  const log = git(repo, ["log", "--format=%H|%h|%an|%as|%s", "--", rel]);
  let md = "# Changelog\n\n*Generated by `fmt changelog` from git history — card changes, not commit hashes.*\n";
  for (const line of (log ? log.split("\n") : [])) {
    const [full, short, author, date, subject] = line.split("|");
    const now = cardsAt(repo, full, rel) ?? [];
    const prev = cardsAt(repo, `${full}^`, rel) ?? [];
    md += `\n## ${date} — ${subject} *(${author}, ${short})*\n\n`;
    if (!prev.length && now.length) { md += `- ${now.length} cards introduced\n`; continue; }
    const byCard = new Map();
    for (const ch of diffCards(prev, now)) {
      if (!byCard.has(ch.card)) byCard.set(ch.card, []);
      byCard.get(ch.card).push(ch);
    }
    for (const [, chs] of byCard) {
      const name = chs[0].name;
      if (chs[0].kind === "added") md += `- **${name}** added\n`;
      else if (chs[0].kind === "removed") md += `- **${name}** removed\n`;
      else md += `- **${name}**: ` + chs.map(c => `${c.field.replace("attributes.", "")} ${JSON.stringify(c.from)} → ${JSON.stringify(c.to)}`).join(", ") + "\n";
    }
  }
  const out = join(gameDir, "CHANGELOG.md");
  writeFileSync(out, md);
  console.log(`Changelog → ${out}`);
}

else if (cmd === "fork") {
  const [src, dst] = rest.map(p => resolve(p));
  execFileSync("git", ["clone", "--bare", src, dst], { stdio: "inherit" });
  try { execFileSync("git", ["-C", dst, "symbolic-ref", "HEAD", "refs/heads/main"]); } catch {}
  console.log(`Forked ${src} → ${dst}\nAttribution lives in history; add an 'attribution:' block to game.yaml for the storefront chain.`);
}

else if (cmd === "release") {
  const gameDir = resolve(rest[0]);
  const version = rest[1];
  if (!/^\d+\.\d+\.\d+$/.test(version ?? "")) { console.error("Usage: release <game-dir> <x.y.z>"); process.exit(2); }
  const repo = repoOf(gameDir);
  const rel = cardsRel(gameDir, repo);
  let prevTag = null;
  try { prevTag = git(repo, ["describe", "--tags", "--abbrev=0"]); } catch {}
  const range = prevTag ? `${prevTag}..HEAD` : "HEAD";
  const now = cardsAt(repo, "HEAD", rel) ?? [];
  const base = prevTag ? (cardsAt(repo, prevTag, rel) ?? []) : [];
  const changes = diffCards(base, now);
  const auto = summarize(changes);
  const notes = `Release v${version}` + (prevTag ? ` (since ${prevTag})` : "") + "\n\n" + (auto ? auto.body : "No card changes.");
  git(repo, ["tag", "-a", `v${version}`, "-m", notes]);
  console.log(`Tagged v${version}\n${notes}`);
}

else if (cmd === "setup") {
  const repo = repoOf(resolve(rest[0] ?? "."));
  git(repo, ["config", "diff.cards.command", `node ${join(TOOLS, "git-diff-cards.mjs")}`]);
  console.log("Semantic `git diff` driver enabled for this clone.");
}

else {
  console.log(`fmt git porcelain — your game is a repo

  save <game-dir> [-m msg]    commit; message auto-written from card changes
  history <game-dir> [-n N]   log as card changes
  changelog <game-dir>        write CHANGELOG.md from history
  fork <src.git> <dst.git>    server-side fork (Remix primitive)
  release <game-dir> <x.y.z>  tag with card changes since last release
  setup [dir]                 enable semantic git diff in this clone`);
  process.exit(cmd ? 2 : 0);
}
